[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[tool.ruff]
include = ["src"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"  # Accepts: "google", "numpy", or "pep257"

[tool.ruff.lint]
select = ["D"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]
